### ISSUE TITLE
Calendar not displaying for dual degree

### ISSUE THREAD

**Issue by EST365** [SeabertYuan/better-workday-calendar#1]
Hi SeabertYuan,

First of all, I really appreciate that you made this extension. It makes Workday's calendar view way more logical (which, I understand, is the whole point of this extension). It does its job well!

As a dual degree, I'm enrolled in both Bachelor of Science and Bachelor of Music. On Workday, they are treated as separate calendars.

![Two_Timetables](https://github.com/user-attachments/assets/f39942b6-b64e-4208-b3d5-c5165330dd9e)

I found that this extension works only for my B.Sc calendar, and not the B.Mus calendar. My B.Mus calendar becomes totally blank when I click "term 1" or "term 2". 

![Blank_Music_Calendar](https://github.com/user-attachments/assets/25d99e87-6772-44f8-b847-3a6f2dfcfcdb)

Is there a way that you can fix this? I've attached some screenshots.

Thanks, and keep up the good work!

EST365

**Comment by SeabertYuan** [comment]
Thank you for this bug report! I will work on a fix for this bug over the next couple of days. When making this extension we did not account for the possibilities of multiple calendars so thank you so much for bringing this issue to our attention!
